export const queryKeys = {
    sessions: ['sessions'] as const,
    session: (sessionId: string) => ['session', sessionId] as const,
    messages: (sessionId: string) => ['messages', sessionId] as const,
    turns: (sessionId: string) => ['turns', sessionId] as const,
    machines: ['machines'] as const,
    machineCodexCredentials: (machineId: string) => ['machine-codex-credentials', machineId] as const,
    previewUrlHistory: ['preview-url-history'] as const,
    groups: ['groups'] as const,
    group: (groupId: string) => ['group', groupId] as const,
    groupMessages: (groupId: string) => ['group-messages', groupId] as const,
    groupTurns: (groupId: string) => ['group-turns', groupId] as const,
    groupNote: (groupId: string) => ['group-note', groupId] as const,
    groupTasks: (groupId: string) => ['group-tasks', groupId] as const,
    memory: ['memory'] as const,
    gitStatus: (sessionId: string) => ['git-status', sessionId] as const,
    sessionFiles: (sessionId: string, query: string) => ['session-files', sessionId, query] as const,
    sessionDirectory: (sessionId: string, path: string) => ['session-directory', sessionId, path] as const,
    sessionFile: (sessionId: string, path: string) => ['session-file', sessionId, path] as const,
    gitFileDiff: (sessionId: string, path: string, staged?: boolean) => [
        'git-file-diff',
        sessionId,
        path,
        staged ? 'staged' : 'unstaged'
    ] as const,
    slashCommands: (sessionId: string) => ['slash-commands', sessionId] as const,
    skills: (sessionId: string) => ['skills', sessionId] as const,
    reviewLoops: ['review-loops'] as const,
    reviewLoop: (loopId: string) => ['review-loop', loopId] as const,
}
