#!/usr/bin/env python3
"""Generate web/src/styles/cursor-agents-home.css with .cursor-agents-home prefix (no @scope)."""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = (REPO / "cursor-clone/styles.css").read_text()


def extract_vars() -> str:
    m = re.search(r":root \{([^}]+)\}", SRC, re.DOTALL)
    if not m:
        raise SystemExit(":root block not found")
    block = m.group(1).strip()
    if "--cursor-bg-hover" not in block:
        block = block.replace(
            "--cursor-bg-quaternary-opaque: #ebebeb;",
            "--cursor-bg-quaternary-opaque: #ebebeb;\n  --cursor-bg-hover: rgba(0, 0, 0, 0.04);",
            1,
        )
    return block


def extract_layout_chunk() -> str:
    start = SRC.find(".app-container {")
    end = SRC.find(
        "/* ==========================================================================\n   6. Chat Page Extensions",
        start,
    )
    if start < 0 or end < 0:
        raise SystemExit("layout chunk boundaries not found")
    return SRC[start:end].rstrip()


def prefix_selector_list(selector_list: str) -> str:
    parts: list[str] = []
    buf: list[str] = []
    depth = 0
    for ch in selector_list:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(buf).strip())
            buf = []
        else:
            buf.append(ch)
    parts.append("".join(buf).strip())
    out: list[str] = []
    for p in parts:
        if not p:
            continue
        if p.startswith("@"):
            out.append(p)
        else:
            out.append(f".cursor-agents-home {p}")
    return ", ".join(out)


def prefix_css_rules(css: str) -> str:
    result: list[str] = []
    i = 0
    n = len(css)
    while i < n:
        if css[i] in " \t\n\r":
            result.append(css[i])
            i += 1
            continue
        if css.startswith("/*", i):
            j = css.find("*/", i + 2)
            if j < 0:
                result.append(css[i:])
                break
            result.append(css[i : j + 2])
            i = j + 2
            continue
        if css[i] == "}":
            result.append("}")
            i += 1
            continue
        if css.startswith("@media", i):
            j = css.find("{", i)
            if j < 0:
                raise SystemExit("@media without {")
            result.append(css[i:j])
            result.append("{")
            i = j + 1
            continue
        j = css.find("{", i)
        if j < 0:
            result.append(css[i:])
            break
        raw_sel = css[i:j].strip()
        body_start = j + 1
        depth = 1
        k = body_start
        while k < n and depth:
            if css[k] == "{":
                depth += 1
            elif css[k] == "}":
                depth -= 1
            k += 1
        body = css[body_start : k - 1]
        if raw_sel:
            result.append(prefix_selector_list(raw_sel))
            result.append("{")
            result.append(prefix_css_rules(body))
            result.append("}")
        else:
            result.append("{")
            result.append(prefix_css_rules(body))
            result.append("}")
        i = k
    return "".join(result)


def main() -> None:
    vars_block = extract_vars()
    chunk = extract_layout_chunk()
    prefixed = prefix_css_rules(chunk)
    # Reset + :scope equivalent
    header = f"""/* Generated by scripts/gen-cursor-agents-home-css.py — do not edit by hand; regen after cursor-clone/styles.css changes */

.cursor-agents-home {{
{vars_block}
}}

.cursor-agents-home *,
.cursor-agents-home *::before,
.cursor-agents-home *::after {{
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}}

.cursor-agents-home {{
  font-family: var(--cursor-font-family-sans);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  background-color: var(--cursor-bg-app);
  color: var(--cursor-text-primary);
  height: 100%;
  min-height: 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  font-size: 13px;
  line-height: 1.5;
}}

"""
    # Flex parent is #root → use 100% not 100vh/100vw; allow main column to shrink-scroll
    prefixed = re.sub(
        r"\.cursor-agents-home \.app-container\{\s*display: flex;\s*height: 100vh;\s*width: 100vw;",
        ".cursor-agents-home .app-container {\n  display: flex;\n  height: 100%;\n  width: 100%;\n  min-height: 0;",
        prefixed,
        count=1,
    )
    prefixed = re.sub(
        r"\.cursor-agents-home \.main-content\{\s*flex: 1;\s*overflow-y: auto;",
        ".cursor-agents-home .main-content {\n  flex: 1;\n  min-height: 0;\n  overflow-y: auto;",
        prefixed,
        count=1,
    )
    out = header + prefixed + "\n"
    dest = REPO / "web/src/styles/cursor-agents-home.css"
    out += "\n/* Reference index uses .sep in agent-subtitle (no rule in clone CSS) */\n"
    out += ".cursor-agents-home .agent-subtitle .sep { display: inline-block; width: 4px; opacity: 0.4; }\n"
    dest.write_text(out)
    print(f"Wrote {dest} ({len(out)} bytes)")


if __name__ == "__main__":
    main()
